version: "3.3"
services:
    database:
        image: postgres:13.1
        container_name: cambly-clone
        ports: 
            - 5432:5432
        environment: 
            POSTGRES_PASSWORD: cambly
        volumes: 
            - ./dbdata:/var/lib/postgresql/data
            - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh